// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlwxcTDit9l0Rnv5yyXC8-ezskSXh5ipg',
    appId: '1:937110070628:web:5c489902be9a786843c671',
    messagingSenderId: '937110070628',
    projectId: 'messager-7a938',
    authDomain: 'messager-7a938.firebaseapp.com',
    storageBucket: 'messager-7a938.appspot.com',
    measurementId: 'G-TBDGNGEFQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChrDZ1S3plu2QyJzlLEqWTKsq_UNXlKBM',
    appId: '1:937110070628:android:828c7ea394ef57da43c671',
    messagingSenderId: '937110070628',
    projectId: 'messager-7a938',
    storageBucket: 'messager-7a938.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHCcm1UXPtUwZkuQqdEDPkxnmCac-O7Gw',
    appId: '1:937110070628:ios:9f3174ca2a7e77fc43c671',
    messagingSenderId: '937110070628',
    projectId: 'messager-7a938',
    storageBucket: 'messager-7a938.appspot.com',
    iosClientId: '937110070628-86898tjtouqakicc65qjg5lfpt5qhhft.apps.googleusercontent.com',
    iosBundleId: 'com.mrdaksh.messager.messager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHCcm1UXPtUwZkuQqdEDPkxnmCac-O7Gw',
    appId: '1:937110070628:ios:15615c0fd3e605d843c671',
    messagingSenderId: '937110070628',
    projectId: 'messager-7a938',
    storageBucket: 'messager-7a938.appspot.com',
    iosClientId: '937110070628-oacoflev71ebpvsvhrln4qo7tthphrb3.apps.googleusercontent.com',
    iosBundleId: 'com.mrdaksh.messager.messager.RunnerTests',
  );
}
